# Generated by Django 5.0.6 on 2024-05-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icons', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('place_1', models.IntegerField()),
                ('place_2', models.IntegerField()),
                ('place_3', models.IntegerField()),
                ('poster', models.ImageField(upload_to='')),
                ('register_price', models.IntegerField()),
                ('mapp', models.FileField(upload_to='')),
                ('path', models.CharField(editable=False, max_length=225, unique=True)),
            ],
        ),
    ]
