# Generated by Django 5.0.6 on 2024-05-19 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sections',
            old_name='icons',
            new_name='icon',
        ),
    ]
