# Generated by Django 5.0.6 on 2024-05-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itfestival', '0002_rename_sponsors_partner_rename_partners_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='information',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speaker',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speaker',
            name='photo',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
